# Generated by Django 5.2.3 on 2025-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('flag_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
